defaults: &defaults
  #cool:
    #saweet: nested settings
  #neat_setting: 24
  admin_emails: ["lifuyuan33@hotmail.com"]

development:
  <<: *defaults
  #neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults


